### ISSUE TITLE
Roadmap for sccthemes

### ISSUE THREAD

**Issue by thomaszwagerman** [thomaszwagerman/sccthemes#1]
A rough, non-linear roadmap for sccthemes.

Contributions and PRs very much welcome.

1. Preparing for minimal release:
- [ ] robust testing suite
- [ ] sound documentation and vignettes
- [ ] r cmd checks all passing

2. Expand range of themes {gt}, shiny/bslib, 

- [ ] reactable
- [ ] gt
- [ ] shiny/bslib

3. Markdown template -> should this be a separate package? Leaning towards yes.
4. Expand geom helper functions

- [ ] geom_line
- [ ] geom_point
- [x] histogram, lollipop etc

5. Expand helper functions beyond ggplot2: 

- [ ] sankey diagram
- [ ] ggmap, sf(?)

**Comment by thomaszwagerman** [comment]
Archiving this repository, closing all issues
